export const ADD_TODO = 'ADD_TODO';
export const DELETE_TODO = 'DELETE_TODO';
export const EDIT_TODO = 'EDIT_TODO';
export const COMPLETE_TODO = 'COMPLETE_TODO';
export const COMPLETE_ALL = 'COMPLETE_ALL';
export const CLEAR_COMPLETED = 'CLEAR_COMPLETED';
export const SYMBOL_SUGGESTIONS_SUCCESS = 'SYMBOL_SUGGESTIONS_SUCCESS';
export const ADD_POSITION = 'ADD_POSITION';
